name: getshareintent_platforminterface
description: Platform interface for the getshareintent plugin, following the federated plugin structure.
version: 0.0.1
author: Simon Wirths
homepage: https://github.com/miraculix92/GetShareIntentPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
